try to handle github python conf issue
* see https://github.com/natverse/fafbseg/actions/runs/13766191349/job/38493130288?pr=213

Run dr_fafbseg() for a status report on your installation
• You do not have python set up for R (required for some fafbseg functions)
  We strongly recommend installing with
  `simple_python()`
  but you can also point the RETICULATE_PYTHON environment variable to a python
  installation that you manage. See the ?simple_python docs for details.
Error: Error in file.info(..., extra_cols = FALSE) : invalid filename argument
Calls: simple_python ... current_python -> structure -> file.mtime -> file.info
Execution halted
Error: Process completed with exit code 1.