fix ubuntu test error with missing arrow lz4
* unrelated to PR ...
* https://github.com/natverse/fafbseg/runs/4040839614?check_suite_focus=true#step:14:182

Error: NotImplemented: Support for codec 'lz4' not built
  In order to read this file, you will need to reinstall arrow with additional features enabled.
  Set one of these environment variables before installing:

   * LIBARROW_MINIMAL=false (for all optional features, including 'lz4')
   * ARROW_WITH_LZ4=ON (for just 'lz4')