switch to ubuntu-latest
* was getting error below on ubuntu 20.04
* arrow::install_pyarrow() was using conda (whereas my install was using pip)
* looks like system mismatch with wheels for conda pyarrow
* maybe I should give an option for virtualenv e.g. for linux systems
* but in the meantime, upgrading from 20.04 to ubuntu-latest like the coverage action will probably solve

Error: Error: Python caveclient installed but I'm having trouble loading it:
 fafbseg::simple_python(pkgs='caveclient') might help
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/runner/.local/share/r-miniconda/envs/r-reticulate/lib/python3.10/site-packages/pyarrow/lib.cpython-310-x86_64-linux-gnu.so)